variable "rgs" {}
variable "vnets" {}
variable "subnets" {}
variable "pips" {}
variable "nsgs" {}
variable "nics" {}
variable "vms" {}
variable "load_balancers" {}
variable "bastions" {}
variable "routes" {}
variable "peering" {}
variable "key_vault" {}
variable "postgresql" {}
variable "private_endpoint" {}
variable "storage" {}
variable "container" {}
variable "blob" {}
variable "firewall" {}